name: Test internally

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:

  test_internally:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazel_mode: [workspace, module]
        include:
          - bazel_mode: module
            bazel_extra_args: "--config=bzlmod"
    env:
      BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Build and test internally (ubuntu-latest, Bazel last_green ${{ matrix.bazel_mode }})

    steps:
      - uses: actions/checkout@v2

      - name: Mount Bazel disk cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel-disk"
          key: bazel-disk-cache-internal

      - name: Build internally
        env:
          USE_BAZEL_VERSION: "last_green"
        run: bazelisk build --config=layering_check ${{ matrix.bazel_extra_args }} --disk_cache="/home/runner/.cache/bazel-disk" //... @fmeum_rules_runfiles_tests//...

      - name: Test internally
        env:
          USE_BAZEL_VERSION: "last_green"
        run: bazelisk test --config=layering_check ${{ matrix.bazel_extra_args }} --disk_cache="/home/runner/.cache/bazel-disk" //... @fmeum_rules_runfiles_tests//...

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: testlogs-internal
          # https://github.com/actions/upload-artifact/issues/92#issuecomment-711107236
          path: |
            ${{ github.workspace }}/bazel-testlogs*/**/test.log
